### PR TITLE
android 12 macos

### LINKED ISSUE #5: build failed on MacOS, version 12.0.1
Platform: Mac OS
version: 12.0.1 
reason: build failed

Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :app:processDebugManifest
/Users/matthew/Downloads/github/FudiNFC/app/src/main/AndroidManifest.xml:15:5-40:19 Warning:
        application@android:label was tagged at AndroidManifest.xml:15 to replace other declarations but no other declaration present

> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/matthew/.gradle/caches/transforms-2/files-2.1/222fb1e9b4241bd7b141674dfe2701ed/core-1.8.0-alpha02/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

the build failed, it's seem that you use the "+" for the version of androidx.core:core-ktx, it should be 1.6.0.

### LINKED ISSUE #7: Android 12 support
App with your library crashes on Android 12 with "`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`"

### PR DESCRIPTION
**Pull request by romellfudi**
- upgraded gradle, added exported tag in manifest
- added pending intent flags
- updated library version
- reverted gitUrl change

### CODE REVIEW

**Comment by romellfudi** [comment]
Please [xuwanjin](https://github.com/xuwanjin) review this epic as to test that everything keeps working as expected

**Comment by SerendipityMatthew** [comment]
I pull the code , build the app. run it on Android 12 phone, it is failed. here is the error:
` AndroidRuntime: Process: com.romellfudi.fudinfc.app, PID: 25508
 AndroidRuntime: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
 AndroidRuntime: 	at androidx.core.view.ViewCompat.<clinit>(ViewCompat.java:2852)
 AndroidRuntime: 	at androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(ViewCompat.java:2534)
 AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:947)
 AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)`
 
I should add desugar for the project according tohe stackoverflow.

**Comment by romellfudi** [comment]
Hello again @xuwanjin & @zigapovhe , I merge the latest changes from you an unique branch, please review in your devices. Thanks in advance

**Comment by SerendipityMatthew** [comment]
build the repo successfully after merge the change.

**Pull request merged**
